### ISSUE TITLE
Only prompt for scanning AH when in rested area or area that is known to have an AH

### ISSUE THREAD

**Issue by TheRealMaxion** [mooreatv/AuctionDB#12]
It's really annoying that the scan reminder comes up every few minutes while out questing, especially that is steals a spacebar press each time, which can cause missing some jumps. Etc.

**Comment by mooreatv** [comment]
You are right, I was optimizing for AH mule but for normal toon it is indeed a pain. Let me find how to fix it while keeping the ah feature

**Comment by TheRealMaxion** [comment]
Thanks, yeah, I noticed that enter was still doing it too, which was annoying when trying to chat. :P
