### ISSUE TITLE
Add option to disable minimap button

### ISSUE THREAD

**Issue by maickel** [mooreatv/AuctionDB#22]
Hi,
Could you implement an option to disable this button ? 
Cheers,
M

**Comment by mooreatv** [comment]
Did you try v0.14, it has SexyMap integration which lets you hide all minimap buttons if you wish?

**Comment by maickel** [comment]
I'm using Elvui like many others, and the button by default is in the middle of the map, I can drag it around but it doesn't fit too much with the framing. It's a really low priority request, but it would be great to have this option !

**Comment by ldemailly** [comment]
I don’t use elvui, can you post a sshot? how are the other addons buttons handled?

**Comment by mooreatv** [comment]
How does Elvui deal with the other addon buttons?

Can you post a screenshot?

**Comment by maickel** [comment]
Elvui doesn't handle those buttons but 99% of the plugins have an option to disable their minimap button.
![elvui](https://user-images.githubusercontent.com/2687492/64592595-ec2bba80-d3de-11e9-97df-60cdf7b39f1b.jpg)

**Comment by mooreatv** [comment]
Agreed it stands out like a sore thumb :)

Curious why they aren’t using some sort of hide buttons unless mousing over the map though, will try to look or indeed option to hide the small button too

**Comment by mooreatv** [comment]
are you sure you used v0.14? because I am told ElvUI works with Libdbicon

**Comment by mooreatv** [comment]
ok I did install elvui to check and it doesn't seem to support the autohide that sexymap does

I'll see what I can do

**Comment by mooreatv** [comment]
ok I wrote this for you:
https://github.com/mooreatv/NeatMinimap/releases

Can you try and see if you love it :)

**Comment by maickel** [comment]
Hi,
Thanks for this ! It looks exactly like what I need, but unfortunately it doesn't seems to work. I've disabled all addons except Elvui/AuctionDB/NeatMinimap and I still have the minimap button :'{
I will try to make some debug tomorrow when there is no queue on my server.

**Comment by mooreatv** [comment]
can you do the following:

/nmm debug 1
/nmm config
all the buttons should show while config is up
click ok (all the buttons should hide after a short bit (the set delay))
/nmm bug

and paste the output here
thanks

**Comment by maickel** [comment]
Since the update you did few hours ago it seems to work properly ! It will be great to have an option to disable the mouseover display too ! With Elvui it will trigger the minibar databar too everytime I mouseover my minimap. I really appreciate your help !

Here is the debug output just in case: 
```Bug Report for NeatMinimap v1.03.03-classic
2019/09/12 07:03:34 +0800 a3a40f0

Bug report from slash command
Session messages log:
34.04 NeatMinimap DBG[1]: Localization not found for "Bug report from slash command"
NeatMinimap bug report open: Please submit on discord or on curse or github or email
34.04 NeatMinimap DBG[1]: Localization not found for "NeatMinimap bug report open: "
34.04 NeatMinimap DBG[1]: Localization not found for "Please submit on discord or on curse or github or email"
34.04 NeatMinimap DBG[1]: Got slash cmd: "bug"
29.02 NeatMinimap DBG[1]: Hiding buttons - force true
29.02 NeatMinimap DBG[1]: Adding "ZGVMarker30Mini"
29.02 NeatMinimap DBG[1]: Adding "ZGVMarker28Mini"
29.02 NeatMinimap DBG[1]: Adding "ZGVMarker26Mini"
29.02 NeatMinimap DBG[1]: Adding "ZGVMarker24Mini"
29.02 NeatMinimap DBG[1]: Adding "ZGVMarker22Mini"
29.02 NeatMinimap DBG[1]: Adding "ZGVMarker20Mini"
29.02 NeatMinimap DBG[1]: Adding "ZGVMarker18Mini"
29.02 NeatMinimap DBG[1]: Adding "ZGVMarker16Mini"
29.02 NeatMinimap DBG[1]: Adding "ZGVMarker14Mini"
29.02 NeatMinimap DBG[1]: Adding "ZGVMarker12Mini"
29.02 NeatMinimap DBG[1]: Adding "ZGVMarker10Mini"
29.02 NeatMinimap DBG[1]: Adding "ZGVMarker8Mini"
29.02 NeatMinimap DBG[1]: Adding "ZGVMarker6Mini"
29.02 NeatMinimap DBG[1]: Adding "ZGVMarker4Mini"
29.02 NeatMinimap DBG[1]: Adding "ZGVMarker2Mini"
29.02 NeatMinimap DBG[1]: Skipping "NeatMinimapFrame" function: 000001C618DC4CD0
29.02 NeatMinimap DBG[1]: Adding "LibDBIcon10_AHDBminimapButton"
29.02 NeatMinimap DBG[1]: Skipping "HelpOpenWebTicketButton" function: 000001C618DC7158
29.02 NeatMinimap DBG[1]: Skipping "HelpOpenTicketButton" function: 000001C618DC7158
29.02 NeatMinimap DBG[1]: Adding "BottomRightMiniPanel"
29.02 NeatMinimap DBG[1]: Adding "BottomLeftMiniPanel"
29.02 NeatMinimap DBG[1]: Adding "TopRightMiniPanel"
29.02 NeatMinimap DBG[1]: Adding "TopLeftMiniPanel"
29.02 NeatMinimap DBG[1]: Skipping "TopMiniPanel" function: 000001C618DC4CD0
29.02 NeatMinimap DBG[1]: Adding "BottomMiniPanel"
29.02 NeatMinimap DBG[1]: Adding "RightMiniPanel"
29.02 NeatMinimap DBG[1]: Adding "LeftMiniPanel"
29.02 NeatMinimap DBG[1]: Adding "ZygorGuidesViewerMapIcon"
29.02 NeatMinimap DBG[1]: Skipping unamed frame/button
29.02 NeatMinimap DBG[1]: Skipping "MMHolder" function: 000001C618DC4CD0
29.02 NeatMinimap DBG[1]: Skipping "MinimapBackdrop" function: 000001C618DC4CD0
29.02 NeatMinimap DBG[1]: Skipping "MiniMapBattlefieldFrame" function: 000001C618DC7158
29.02 NeatMinimap DBG[1]: Skipping "MiniMapMailFrame" function: 000001C618DC4CD0
29.02 NeatMinimap DBG[1]: Skipping "MiniMapTrackingFrame" function: 000001C618DC4CD0
29.02 NeatMinimap DBG[1]: ElvUI case, we'll start with fewer managed buttons
29.02 NeatMinimap DBG[1]: NMM.optionsPanel.okay() internal
19.39 NeatMinimap DBG[1]: Showing buttons - force nil
19.39 NeatMinimap DBG[1]: Calling Init() on all 10 children
19.39 NeatMinimap DBG[1]: Options Panel refresh!
19.39 NeatMinimap DBG[1]: Got slash cmd: "config"
NeatMinimap debug now 1
NeatMinimap v1.03.03-classic by MooreaTv: type /nmm for command list/help.
```

**Comment by mooreatv** [comment]
Sorry I'm very unfamiliar with elvui and thank you for your patience with this but...
what does " it will trigger the minibar databar too everytime I mouseover my minimap" mean, what is the databar/how can see/reproduce this (/what's the issue)?

**Comment by mooreatv** [comment]
hmmm I have to exclude ZGVMarker14Mini too

**Comment by maickel** [comment]
The minimap databar is a little bar under the minimap that will show some broker informations, by default guilds/friends online. I did a little screenshot with red stroke.
![minmap](https://user-images.githubusercontent.com/2687492/64742404-b1d13300-d52e-11e9-953f-3c26556113c1.jpg)

**Comment by mooreatv** [comment]
ic so you don't like to hide this part when not moused in? you want to see it all the time?
(it's a bit on purpose I hide those, only keeping the topinfo so far because they seems not very useful but I should probably at least make it an option? yet curious, does it matter to see # of guildmates all the time?)

**Comment by maickel** [comment]
No by default it's hidden, and I want it to be hidden. But with NeatMinimap enable it will make it show on mouseover.

**Comment by mooreatv** [comment]
ohhh it comes back while you hid it from within the elvui interface, ic... I'll try to find that option in their huge menu to repro

**Comment by mooreatv** [comment]
can you do me a favor an sshot the output of

/dump ZGVMarker4Mini

or any of the mentioned ZGVMarker* in the debug output (numbers probably change at each reload; it shouldn't be a blue table with ZGVMarker4Mini={...some stuff not empty...}

**Comment by maickel** [comment]
No worries, here it is : 
```lua
Dump: ZGVMarker4Mini 
ZGVMarker4Mini={ 
  [0]=<userdata ZGVMarker4Mini[0]>, 
  arrow={ 
    [0]=<userdata>, 
    PixelSnapDisabled=true 
  }, 
  waypoint={ 
    source={ 
      map=1446, 
      x=0.5999, 
      floor=0, 
      waypoint=ZGVMarker4Mini.waypoint, 
      y=0.3702 
    }, 
    frame_minimap=ZGVMarker4Mini, 
    m=1446, 
    icon={ 
      edgesize=25, 
      minimap_alpha=0.5, 
      spinner=true, 
      alpha=0.5, 
      rotates=false, 
      onminimap="always", 
      tex={ 
        r=1, 
        b=1, 
        file="mapicons", 
        g=1, 
        coords={ 
          [1]=0.5, 
          [2]=1, 
          [3]=0, 
          [4]=0.5 
        } 
      }, 
      minisize=31.499999165535, 
      edgetex={ 
        r=1, 
        b=1, 
        file="mapicons", 
        g=1, 
        coords={ 
          [1]=0, 
          [2]=0.5, 
          [3]=0.5, 
          [4]=1 
        } 
      }, 
      size=26.999999284744 
    }, 
    map=1446, 
    type="way", 
    frame_taximap={ 
      [0]=<userdata ZGVMarker4Taxi[0]>, 
      icon={ 
        [0]=<userdata>, 
        PixelSnapDisabled=true 
      }, 
      waypoint=ZGVMarker4Mini.waypoint 
    }, 
    frame_worldmap={ 
      [0]=<userdata ZGVMarker4World[0]>, 
      zoom={ 
        [0]=<userdata> 
      }, 
      spinner={ 
        [0]=<userdata ZGVMarker4WorldSpinner[0]>, 
        PixelSnapDisabled=true 
      }, 
      label={ 
        [0]=<userdata ZGVMarker4WorldLabel[0]> 
      }, 
      unzoom={ 
        [0]=<userdata> 
      }, 
      Loop={ 
        [0]=<userdata> 
      }, 
      waypoint=ZGVMarker4Mini.waypoint, 
      icon={ 
        [0]=<userdata>, 
        PixelSnapDisabled=true 
      }, 
      zoomy={ 
        [0]=<userdata> 
      } 
    }, 
    y=0.3702, 
    x=0.5999, 
    title="Tanaris 59,37", 
    showonedge=true, 
    num=5, 
    onminimap="always", 
    c=1414, 
    overworld=true 
  }, 
  isZygorWaypoint=true, 
  minimap_count=0.079000004101545, 
  lastdist=927.38214825183, 
  is_on_edge=true, 
  icon={ 
    [0]=<userdata>, 
    PixelSnapDisabled=true 
  }, 
  dist=927.38214825183 
} ```

**Comment by mooreatv** [comment]
awesome thanks, I'll use .waypoint to skip those

I haven't found yet how you hide the guild/friends things, it doesn't seem to be in the minimap options or I am blind (/ec and then?)

**Comment by mooreatv** [comment]
Found it with help from discord, in datatexts

**Comment by maickel** [comment]
I've tried to do a quick monkeypatch adding an option doMouseover in settings : 
```lua
local doMouseover = p:addCheckBox(L["Mouseover"], L["Show buttons on mouseover"])
                    :Place(4, 20)
```

and putting a condition in this function : 

```lua
function NMM:SetupMouseInOut()
  NMM:UpdateButtons()
  local name = "NeatMinimapFrame"
  local f = NMM.minimapframe or NMM:Frame(name, name, nil, Minimap)
  NMM.minimapframe = f
  f:ClearAllPoints()
  local border = 25
  f:SetPoint("BOTTOMLEFT", -border, -border)
  f:SetPoint("TOPRIGHT", border, border)
  f:SetFrameStrata("BACKGROUND")
  f:EnableMouse(false)
  if NMM.doMouseover then
    -- f:Show()
    f:SetScript("OnEnter", function()
      NMM:ShowButtons()
    end)
    f:SetScript("OnLeave", function()
      NMM:ScheduleNextCheck()
    end)
    Minimap:HookScript("OnEnter", function()
      NMM:ShowButtons()
    end)
    Minimap:HookScript("OnLeave", function()
      NMM:ScheduleNextCheck()
    end)
  end

  NMM:ForceUpdate()
end
```
Seems to work properly, but pretty sure it must be dirty as I'm not really used to Lua and WoW API.

**Comment by mooreatv** [comment]
is the objective to never show any of the hidden stuff? can I ask why (if you’re mousing over there would you still not want to use / see buttons?)

would delaying showing or adding a modifier cover your case?

Laurent

**Comment by maickel** [comment]
Yes I really do not need those minibuttons, the goal for me is to remove them all ! (ahah) Most of the time I can access settings in the Interface Options panel or by typing the command in chat. Otherwhise I have a Data Broker Display (Bazooka, like you can see on the screenshot few posts above) that will show few addons that I really need to access quickly.

**Comment by b-morgan** [comment]
This is an interesting thread but I like to second @maickel request to simply add an option to disable the minimap button. Adding a ton of other addons just to accomplish this one simple task doesn't make a whole lot of sense.

**Comment by b-morgan** [comment]
Yikes! Sexymap is way over the top and Neatminimap doesn't solve the problem, it just hides it.
The problem is that there are too many addons that want to have a minimap icon and there just isn't enough space. Adding a radius option would help a little bit but much better solutions, IMO, are Auctioneer's SlideBar or an LDB addon like Titan, Bazooka, etc.

Bottom line, I want to control which addons get to use the precious minimap border. I don't want addons to dictate what buttons I have and what buttons I don't have. AHDB doesn't make the cut and I may disable the whole addon until this issue is resolved.

**Comment by mooreatv** [comment]
done in v1.04.00 Oct 18th 2020
