### ISSUE TITLE
Tooltip prices

### ISSUE THREAD

**Issue by choigit** [mooreatv/AuctionDB#24]
Do the tooltip prices only reflect your most recent scan, or are they some sort of weighted average (e.g., dbminbuyout/AuctionDB in TSM)? Thanks!

**Comment by choigit** [comment]
Figured it out! Lol

**Comment by mooreatv** [comment]
for reference: right now (v0.14) it's only the most recent scan data (ie only "true price" you can buy at the moment) but we record everything and more will be used in the future
