### ISSUE TITLE
AHDB offline mode not implemented yet, confusing

### ISSUE THREAD

**Issue by ltmote** [mooreatv/AuctionDB#25]
After I have scanned the AH, I attempt to use the LEFT click to bring up the DB and get this error

AHDB: manual scan requested...
AHDB Warning: Can't query ALL at AH, try again later...

**Comment by ltmote** [comment]
And then when I am away from AH it says   Not at an AH Can't scan...

However I want to pull the Offline Mode

**Comment by mooreatv** [comment]
sorry the offline mode isn't there yet, you can only scan and record (and see the last scan through tooltip or offline analysis out of game)
