### ISSUE TITLE
AuctionDBSaved = {["itemDB_2"]

### ISSUE THREAD

**Issue by alex93skr** [mooreatv/AuctionDB#28]
question: please tell us about the format of the string with colons:

`AuctionDBSaved = {["itemDB_2"] [:::: ...]}`

in it I see numbers that I don’t come across during parsing `["ah"] ["data"]`, and I don’t understand what they mean.

and another request: could you add to itemDB - Vendor Price? it would help a lot with off-line analytics

the addon is just super and your utility AHDBapp helps! thank)

**Comment by mooreatv** [comment]
item db keys are compressed/useful part of the item string, see
https://github.com/mooreatv/MoLib/blob/master/MoLibAH.lua#L17-L48

**Comment by mooreatv** [comment]
closing this now, you can also see
https://github.com/mooreatv/AHDBapp
for how the data gets imported to a SQL database
