### ISSUE TITLE
Where is the Database?

### ISSUE THREAD

**Issue by ChrisPasda** [mooreatv/AuctionDB#31]
Hi,

i downloaded the Addon and tryed to find out where the database is saved. 
Can anybody please tell me?

With best regards

**Comment by mooreatv** [comment]
As mentioned in https://github.com/mooreatv/AHDBapp
the db is saved in saved vars:

e.g. "c:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\YOURACCOUNT\SavedVariables\AuctionDB.lua"

**Comment by Peneheals** [comment]
The readme states:

`You will be able to later query that DB even when not at the AH`

I tried to find out where and how can I do this search, without any success. There is a mention here about the lack of implementation: https://github.com/mooreatv/AuctionDB/issues/25#issuecomment-530144625

Meanwhile here above, @mooreatv you wrote that it may be possible through another addon, the AHDBapp. There is no proper documentation about the query system, and it would be great to have that. I'm ready to create one and extend the docs with an MR, but it would be great to point me to the right direction. I'm seeing that there is a [script](https://github.com/mooreatv/AHDBapp/blob/master/ahdbSavedVars2Json.sh) in the app folder which may be does this. Is it the - I know WIP - way to query the offline db locally? Or are there any in-game solution?

(I'm playing from Mac, not Windows.)

**Comment by mooreatv** [comment]
Out of game DB is populated using https://github.com/mooreatv/AHDBapp

The Go version (the script is older) reads directly the saved variable and populates a MySql DB 

MySQL is a very common DB that has "SQL" as the query language as well as plenty of UI/front ends (you can google)
