### ISSUE TITLE
Strange scanning behavior

### ISSUE THREAD

**Issue by jshellen** [mooreatv/AuctionDB#32]
Hi,

Is this expected behavior: after restarting the game and running /ahdb scan the scan finishes successfully. Now, if I do it immediately again I get warning message "AHDB Warning: Can't query ALL at AH, try again later...". 

Is this expected behavior? Am I doing something wrong?

Thanks

**Comment by mooreatv** [comment]
The wow full scan api lets you only scan every 15 minutes if you exit the AH or do any other AH search between scans. It so happens you can scan more frequently (clicking the minimap button or logging out and back in) but I don't think that's intended by blizzard
