### ISSUE TITLE
AuctionDB spams chat

### ISSUE THREAD

**Issue by Martan404** [mooreatv/AuctionDB#35]
Every time I open addon interface settings, even without opening AuctionDB settings, it keeps sending messages to my chat stating "AHDB: options screen cancelled, not making any changes."

I have debug level to 0 and no way to disable this message. Being able to get rid of it would be appreciated. I'm using the WoW Classic version

Bug Report for AuctionDB v1.03.01
2020/09/18 09:21:34 +0200 caba7af

Bug report from slash command
Session messages log:
AHDB bug report open: Please submit on discord or https://bit.ly/ahbug or email
AHDB: options screen cancelled, not making any changes.
AHDB: options screen cancelled, not making any changes.
AHDB bug report open: Please submit on discord or https://bit.ly/ahbug or email
AHDB: options screen cancelled, not making any changes.
AHDB v1.03.01 by MooreaTv: type /ahdb for command list/help.

**Comment by mooreatv** [comment]
that should be gone now
