### ISSUE TITLE
BCC - Pagination Missing

### ISSUE THREAD

**Issue by holicraap** [mooreatv/AuctionDB#38]
Since the update 6  days ago, pagination is missing on the buy page.

**Comment by mooreatv** [comment]
Thanks for filling an issue but

I think you might be confusing addons, as AHDB (https://www.curseforge.com/wow/addons/auction-house-database) this addon, doesn't have a buy UI

Reopen with a lot more details if needed (which game, version, `/ahdb bug` output etc)
