### ISSUE TITLE
BCC - Can't sell "of the ###" items

### ISSUE THREAD

**Issue by holicraap** [mooreatv/AuctionDB#39]
Since update 6 days ago, whenever trying to list a green item "of the whale/wolf etc" the item doesn't list and AHDB gives an error that won't let me list any other items until I close and reopen the AH window. "AuctionBuddy: Can't post new items at this moment, try again in a few seconds."

**Comment by mooreatv** [comment]
Thanks for filling another issue but again

I think you might be confusing addons, as AHDB (https://www.curseforge.com/wow/addons/auction-house-database) this addon, doesn't have a sell UI either

Reopen with a lot more details if needed (which game, version, `/ahdb bug` output , actual error, screenshots etc)
